# IS 362 â€“ Week 5 Assignment

** For this weeks task we must answer the following questions:**

1. What is the northernmost airport in the United States?
2. What is the easternmost airport in the United States?
3. On February 12th, 2013, which New York area airport had the windiest weather?

In [1]:
#First we need to import pandas
import pandas as pd

The CSV files for this assignment can be found at the following link: https://github.com/hadley/nycflights13/tree/master/data-raw

In [3]:
#Next we need to write a .read_csv() command to retrieve the airports data
airports_data = pd.read_csv('https://raw.githubusercontent.com/hadley/nycflights13/master/data-raw/airports.csv')

**Question 1: What is the northernmost airport in the United States?**

We will need to use the latitudinal informotion provided in the table below to answer this question.

In [4]:
#The following code will return a table with data sorted by latitude ascending
airports_data.sort_values(by=['lat'], ascending=False).head()

,faa,name,lat,lon,alt,tz,dst,tzone
417,EEN,Dillant Hopkins Airport,72.270833,42.898333,149,-5.0,A,\N
230,BRW,Wiley Post Will Rogers Mem,71.285446,-156.766003,44,-9.0,A,America/Anchorage
110,AIN,Wainwright Airport,70.638056,-159.994722,41,-9.0,A,America/Anchorage
708,K03,Wainwright As,70.613378,-159.860350,35,-9.0,A,America/Anchorage
152,ATK,Atqasuk Edward Burnell Sr Memorial Airport,70.467300,-157.436000,96,-9.0,A,America/Anchorage

According to the table above Dillant Hopkins Airport is the northernmost airport in the US

But this is incorrect... because according to google maps Wiley Post-Will Rogers Mem Airport is actually the northern most airport in the US.

*
https://www.google.com/maps/place/Wiley+Post-Will+Rogers+Memorial+Airport/@70.9704186,-140.4461716,3z/data=!4m5!3m4!1s0x50c327fff620aae7:0x936de8c8fd2d094b!8m2!3d71.284909!4d-156.766362?hl=en *

**Question 2: What is the easternmost airport in the US?**

We will need to use the longitudinal information provided in the table below to answer this question.

In [5]:
#The following code will return a table with data sorted by longitude ascending
airports_data.sort_values(by=['lon'], ascending=False).head()

,faa,name,lat,lon,alt,tz,dst,tzone
1290,SYA,Eareckson As,52.712275,174.113620,98,-9.0,A,America/Anchorage
942,MYF,Montgomery Field,32.475900,117.759000,17,8.0,A,Asia/Chongqing
396,DVT,Deer Valley Municipal Airport,33.411700,112.457000,1478,8.0,A,Asia/Chongqing
417,EEN,Dillant Hopkins Airport,72.270833,42.898333,149,-5.0,A,\N
444,EPM,Eastport Municipal Airport,44.910111,-67.012694,45,-5.0,A,America/New_York

According to the table above Eareckson Airport is the easternmost airport in the US

But this is incorrect... because according to google maps Eastport Municipal Airport is actually the easternmost airport in the US.

*
https://www.google.com/maps/place/Eastport+Municipal+Airport/@45.0809204,-67.4577252,9z/data=!4m5!3m4!1s0x4ca8bcbb416bb557:0xe8e7c4805bb5f1e8!8m2!3d44.9099999!4d-67.012779?hl=en*

** Question 3: On February 12th, 2013, which New York area airport had the windiest weather? **

We will need to use the weather information provided in the table below to answer this question.

In [6]:
#we need to write a .read_csv() command to retrieve the weather data
weather_data = pd.read_csv("https://raw.githubusercontent.com/hadley/nycflights13/master/data-raw/weather.csv")

In [9]:
#The following code will return a table with the weather data for the specific date (Feb 12th 2013)
weather_data[(weather_data["month"]==2) & (weather_data["day"]==12) & (weather_data["year"]==2013)].sort_values(by=["wind_speed"], ascending=False).head()

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
1015,EWR,2013,2,12,8,39.02,26.96,61.63,260.0,1048.36058,1206.432388,0.0,1008.3,10.0,2013-02-12T08:00:00Z
18433,LGA,2013,2,12,7,42.98,26.06,50.94,290.0,23.01560,26.485892,0.0,1007.1,10.0,2013-02-12T07:00:00Z
1024,EWR,2013,2,12,17,44.06,26.06,48.87,270.0,21.86482,25.161598,0.0,1012.5,10.0,2013-02-12T17:00:00Z
18444,LGA,2013,2,12,18,44.06,23.00,43.02,300.0,21.86482,25.161598,0.0,1011.7,10.0,2013-02-12T18:00:00Z
9728,JFK,2013,2,12,13,42.08,24.08,48.56,280.0,20.71404,23.837303,0.0,1011.6,10.0,2013-02-12T13:00:00Z

According to the table above Newark Airport(EWR) had the windiest weather on Feb 12th 2013.

But this is incorrect... because the data is unrealistic and seems there seems to be a mistake. 

This means *Laguardia airport (LGA)* was actually the windiest airport, since it had the highest wind speed & wind gust on the day.